name: Build and push on release (new tag)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Call linter
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: Get tag
        id: get_tag
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}
      - name: Build code
        uses: borales/actions-yarn@v2.0.0
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
          REACT_APP_GIT_SHA: ${{ github.sha }}
          REACT_APP_VERSION: ${{ env.GIT_TAG }}
        with:
          cmd: build
      - name: Publish to quay.io
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: ocpmetal/ocp-metal-ui
          username: ${{ secrets.QUAYIO_OCPMETAL_USERNAME }}
          password: ${{ secrets.QUAYIO_OCPMETAL_PASSWORD }}
          registry: quay.io
          dockerfile: Dockerfile
          tags: 'latest,${{ env.GIT_TAG }},${{ github.sha }}'
      - name: Publish integration tests to quay.io
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: ocpmetal/ocp-metal-ui-tests
          username: ${{ secrets.QUAYIO_OCPMETAL_USERNAME }}
          password: ${{ secrets.QUAYIO_OCPMETAL_PASSWORD }}
          registry: quay.io
          dockerfile: Dockerfile.cypress
          tags: 'latest,${{ env.GIT_TAG }},${{ github.sha }}'
